### ISSUE TITLE
Cascading LOV doesn't work for multiple parents

### ISSUE THREAD

**Issue by Cristian-I** [bostrowski/Pretius-APEX-Enhanced-Lov-Item#15]
Hey,

I found that if you add an plugin item with more than one Cascading LOV Parent Item the refresh of the plugin item will be triggered on change of just the first Cascading LOV Parent and not for any of the other Cascading LOV Parent Items.

For a quick fix i've replaced in the enhanceLovItem.js file where i found
`this.options.item.lov_cascade_parent_items` with
`this.options.item.lov_cascade_parent_items.replace(/,/g, ", #")`

Hope it helps.

**Comment by bostrowski** [comment]
@Cristian-I 
It is the bug and it will be fixed in `v1.0.5` which I'm working on. 

Its about using function `apex_plugin_util.page_item_names_to_jquery` for 2 attributes in the plugin package body (lines **165** and **166**) and removing `#` from JS code in lines **119** and **342**.

Thank you for your feedback!
